services:
  - type: web
    name: cyberlab-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start

    envVars:
      - key: MONGO_URI
        sync: false

    aptPackages:
      - nmap